# Generated by Django 5.1.6 on 2025-04-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0003_rubric_spare_goiteen_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(help_text='Назва рубрики', max_length=50),
        ),
    ]
