# Generated by Django 5.1.6 on 2025-04-16 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0004_alter_rubric_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва продукту')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис продукту')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
        ),
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('completed', 'Завершено'), ('canceled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Market.product2', verbose_name='Продукт')),
            ],
        ),
    ]
