# Generated by Django 5.2.1 on 2025-06-01 15:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='rate',
        ),
        migrations.AddField(
            model_name='stuff',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stuff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stuffs/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='stuff_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг товару')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='shop.stuff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('stuff', 'user')},
            },
        ),
    ]
