# Generated by Django 5.2.2 on 2025-06-08 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_stuff_rate_stuff_create_at_stuff_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.stuff', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Кошик',
                'unique_together': {('user', 'stuff')},
            },
        ),
    ]
